#!/usr/bin/env node
/**
 * build.js — assembles the static site.
 *
 * Authored sources live in src/pages/*.html and use include markers:
 *
 *     <!-- @include components/header.html -->
 *
 * This script replaces each marker with the contents of that file and writes
 * the result to the site root (src/pages/home.html -> index.html, everything
 * else -> pages/<name>.html).
 *
 * Why a build step at all: the site is opened straight from disk, and fetch()
 * on file:// is blocked, so runtime partial injection would silently drop the
 * header and footer. Inlining at build time works from file://, from any
 * static host, and in the Claude Design preview alike.
 *
 * Generated files are overwritten on every run — edit src/pages/, never the
 * output.
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src", "pages");
const INCLUDE = /^([ \t]*)<!--\s*@include\s+(\S+?)\s*-->[ \t]*$/gm;
const MAX_DEPTH = 10;

const GENERATED = "<!-- GENERATED by build.js from src/pages/ — do not edit. -->";

/** Recursively expand @include markers, preserving the marker's indentation. */
function expand(html, fromFile, depth = 0) {
  if (depth > MAX_DEPTH) {
    throw new Error(`@include nested deeper than ${MAX_DEPTH} in ${fromFile}`);
  }
  return html.replace(INCLUDE, (_match, indent, relPath) => {
    const target = resolve(ROOT, relPath);
    if (!target.startsWith(ROOT)) {
      throw new Error(`@include escapes the project root: ${relPath}`);
    }
    let part;
    try {
      part = readFileSync(target, "utf8");
    } catch {
      throw new Error(`@include target not found: ${relPath} (in ${fromFile})`);
    }
    return expand(part, relPath, depth + 1)
      .replace(/\n$/, "")
      .split("\n")
      .map((line) => (line.trim() ? indent + line : line))
      .join("\n");
  });
}

/**
 * Output pages resolve assets relative to themselves, so src/ is authored with
 * root-relative "./" paths and rewritten to "../" for anything under pages/.
 */
function rebase(html, depthFromRoot) {
  if (depthFromRoot === 0) return html;
  const up = "../".repeat(depthFromRoot);
  return html.replace(
    /(\s(?:href|src|srcset|data-src|poster)=")\.\/([^"]*)"/g,
    (_m, attr, rest) => `${attr}${up}${rest}"`
  );
}

function build() {
  const files = readdirSync(SRC).filter((f) => f.endsWith(".html"));
  if (!files.length) throw new Error("no pages found in src/pages/");

  mkdirSync(join(ROOT, "pages"), { recursive: true });

  for (const file of files) {
    const name = file.replace(/\.html$/, "");
    const isHome = name === "home";
    const depth = isHome ? 0 : 1;
    const outPath = isHome
      ? join(ROOT, "index.html")
      : join(ROOT, "pages", file);

    const src = readFileSync(join(SRC, file), "utf8");
    const out = rebase(expand(src, `src/pages/${file}`), depth);

    writeFileSync(outPath, `${GENERATED}\n${out}`);
    console.log(`  ${("src/pages/" + file).padEnd(28)} -> ${isHome ? "index.html" : "pages/" + file}`);
  }
  console.log(`\nBuilt ${files.length} page${files.length === 1 ? "" : "s"}.`);
}

try {
  build();
} catch (err) {
  console.error(`\nBuild failed: ${err.message}\n`);
  process.exit(1);
}
