#!/usr/bin/env node
/**
 * build.js — assembles the static site.
 *
 * Authored sources live in src/pages/*.html and use include markers:
 *
 *     <!-- @include components/header.html -->
 *
 * This script replaces each marker with the contents of that file and writes
 * the result to the site root (src/pages/home.html -> index.html, everything
 * else -> pages/<name>.html).
 *
 * Why a build step at all: the site is opened straight from disk, and fetch()
 * on file:// is blocked, so runtime partial injection would silently drop the
 * header and footer. Inlining at build time works from file://, from any
 * static host, and in the Claude Design preview alike.
 *
 * Generated files are overwritten on every run — edit src/pages/, never the
 * output.
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, cpSync } from "node:fs";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSync } from "esbuild";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src", "pages");
const INCLUDE = /^([ \t]*)<!--\s*@include\s+(\S+?)\s*-->[ \t]*$/gm;
const SCRIPT = /^([ \t]*)<!--\s*@script\s+([\w-]+)\s*-->[ \t]*$/gm;
const MAX_DEPTH = 10;

const GENERATED = "<!-- GENERATED by build.js from src/pages/ — do not edit. -->";

/** Recursively expand @include markers, preserving the marker's indentation. */
function expand(html, fromFile, depth = 0) {
  if (depth > MAX_DEPTH) {
    throw new Error(`@include nested deeper than ${MAX_DEPTH} in ${fromFile}`);
  }
  return html.replace(INCLUDE, (_match, indent, relPath) => {
    const target = resolve(ROOT, relPath);
    if (!target.startsWith(ROOT)) {
      throw new Error(`@include escapes the project root: ${relPath}`);
    }
    let part;
    try {
      part = readFileSync(target, "utf8");
    } catch {
      throw new Error(`@include target not found: ${relPath} (in ${fromFile})`);
    }
    return expand(part, relPath, depth + 1)
      .replace(/\n$/, "")
      .split("\n")
      .map((line) => (line.trim() ? indent + line : line))
      .join("\n");
  });
}

/**
 * Bundle js/main.js plus one page module into a single classic script.
 *
 * The source is ES modules, but <script type="module"> is CORS-blocked on
 * file://, and this site is opened by double-clicking the page as well as
 * being served. A classic IIFE bundle runs in both, and collapses the module
 * request waterfall into one file.
 */
function bundle(pageModule) {
  mkdirSync(join(ROOT, "js", "build"), { recursive: true });
  const entry = join(ROOT, "js", "build", `.${pageModule}.entry.js`);
  const imports = [`import "../main.js";`];
  if (pageModule !== "none") imports.push(`import "../pages/${pageModule}.js";`);
  writeFileSync(entry, imports.join("\n") + "\n");
  try {
    buildSync({
      entryPoints: [entry],
      outfile: join(ROOT, "js", "build", `${pageModule}.js`),
      bundle: true,
      format: "iife",
      target: "es2020",
      legalComments: "none",
      banner: { js: "/* GENERATED by build.js from js/ — do not edit. */" }
    });
  } finally {
    rmSync(entry, { force: true });
  }
}

/**
 * Output pages resolve assets relative to themselves, so src/ is authored with
 * root-relative "./" paths and rewritten to "../" for anything under pages/.
 */
function rebase(html, depthFromRoot) {
  if (depthFromRoot === 0) return html;
  const up = "../".repeat(depthFromRoot);
  return html.replace(
    /(\s(?:href|src|srcset|data-src|poster)=")\.\/([^"]*)"/g,
    (_m, attr, rest) => `${attr}${up}${rest}"`
  );
}

/**
 * Assemble dist/ — exactly what a host should serve, and nothing else.
 *
 * The build writes into the project root so the site can also be opened
 * straight from disk, but that root also holds the authored sources, the
 * build script and the unbundled modules. None of those belong on a public
 * server, so deployment copies out only the files the browser actually asks
 * for. assets/raw/ (the untracked video masters) is excluded too.
 */
function dist() {
  const OUT = join(ROOT, "dist");
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  const copy = (rel, filter) =>
    cpSync(join(ROOT, rel), join(OUT, rel), { recursive: true, filter });

  copy("index.html");
  copy("pages");
  copy("css");
  copy("js/build");
  copy("assets", (src) => !src.includes(`${sep}assets${sep}raw`));

  console.log(`\nAssembled dist/ — deploy that directory.`);
}

function build() {
  const files = readdirSync(SRC).filter((f) => f.endsWith(".html"));
  if (!files.length) throw new Error("no pages found in src/pages/");

  mkdirSync(join(ROOT, "pages"), { recursive: true });

  for (const file of files) {
    const name = file.replace(/\.html$/, "");
    const isHome = name === "home";
    const depth = isHome ? 0 : 1;
    const outPath = isHome
      ? join(ROOT, "index.html")
      : join(ROOT, "pages", file);

    const src = readFileSync(join(SRC, file), "utf8");
    let out = expand(src, `src/pages/${file}`);

    out = out.replace(SCRIPT, (_m, indent, mod) => {
      bundle(mod);
      return `${indent}<script src="./js/build/${mod}.js" defer></script>`;
    });

    out = rebase(out, depth);

    writeFileSync(outPath, `${GENERATED}\n${out}`);
    console.log(`  ${("src/pages/" + file).padEnd(28)} -> ${isHome ? "index.html" : "pages/" + file}`);
  }
  console.log(`\nBuilt ${files.length} page${files.length === 1 ? "" : "s"}.`);
}

try {
  build();
  if (process.argv.includes("--dist")) dist();
} catch (err) {
  console.error(`\nBuild failed: ${err.message}\n`);
  process.exit(1);
}
